name: Production Release Pipeline

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Enter version (e.g., 1.2.3). Leave empty for auto patch bump."
        required: false
        default: ""

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: \${{ vars.RUBRION_APP_ID }}
          private-key: \${{ secrets.RUBRION_APP_SECRET }}

      - name: Set Git User Identity
        run: |
          git config --global user.name "Rubrion"
          git config --global user.email "rubrion[bot]@users.noreply.github.com"

      - name: Checkout Develop Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop
          token: \${{ steps.app-token.outputs.token }}
      
      - name: Ensure Develop is Up to Date
        run: |
          git fetch origin develop
          git checkout develop
          git pull origin develop
      
      - name: Merge Develop into Main
        run: |
          git checkout main
          git merge --no-ff develop
          git push origin main
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Determine Release Version
        id: version
        run: |
          if [ -n "\${{ github.event.inputs.release_version }}" ]; then
            VERSION=\${{ github.event.inputs.release_version }}
          else
            LAST_TAG=\$(git tag --sort=-v:refname | head -n 1 | sed 's/v//')
            IFS='.' read -r major minor patch <<< "\$LAST_TAG"
            VERSION="\$major.\$minor.\$((patch + 1))"
          fi
          echo "VERSION=\$VERSION" >> \$GITHUB_ENV
          echo "Release version set to \$VERSION"
      
      - name: Verify Version in Code
        run: |
          VERSION_IN_CODE=$(grep "CurrentVersion =" internal/commands/version.go | awk -F'"' '{print $2}')
          echo "Version in code: $VERSION_IN_CODE"
          echo "Expected version: $VERSION"
          
          if [ "$VERSION_IN_CODE" != "$VERSION" ]; then
            echo "ERROR: Version mismatch detected!"
            echo "The version in internal/commands/version.go ($VERSION_IN_CODE) does not match the release version ($VERSION)."
            echo "Please update the CurrentVersion in internal/commands/version.go to $VERSION and run the workflow again."
            exit 1
          else
            echo "Version check passed: Code version matches release version."
          fi

      - name: Generate Changelog
        run: |
          npx conventional-changelog-cli -p angular -o docs/CHANGELOG.md
          git add docs/CHANGELOG.md
          git commit -m "docs: release v${VERSION} [skip ci]"
          git push origin main

      - name: Create Git Tag
        run: |
          git tag "v\${VERSION}"
          git push origin --tags

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build Cross-Platform Binaries
        run: |
          if [ -z "\${{ vars.PROJECT_NAME }}" ]; then
            echo "ERROR: PROJECT_NAME GitHub variable is not set. Please set it in repository settings."
            exit 1
          fi
          
          PROJECT_NAME="\${{ vars.PROJECT_NAME }}"
          echo "Using project name: \$PROJECT_NAME"
          
          go mod tidy
          echo "Building CLI for version \$VERSION"
          mkdir -p dist
      
          GOOS=linux GOARCH=amd64 go build -o dist/\$PROJECT_NAME-linux -ldflags="-X '\$PROJECT_NAME/commands.CurrentVersion=\${VERSION}'" main.go || exit 1
          GOOS=windows GOARCH=amd64 go build -o dist/\$PROJECT_NAME.exe -ldflags="-X '\$PROJECT_NAME/commands.CurrentVersion=\${VERSION}'" main.go || exit 1
          GOOS=darwin GOARCH=amd64 go build -o dist/\$PROJECT_NAME-mac -ldflags="-X '\$PROJECT_NAME/commands.CurrentVersion=\${VERSION}'" main.go || exit 1
      
          echo "Build completed. Contents of dist/:"
          ls -lh dist/

      - name: Create GitHub Release
        run: |
          PROJECT_NAME="\${{ vars.PROJECT_NAME }}"
          gh release create "v\${VERSION}" \
            --title "Release v\${VERSION}" \
            --notes-file CHANGELOG.md \
            dist/\$PROJECT_NAME-linux dist/\$PROJECT_NAME.exe dist/\$PROJECT_NAME-mac
        env:
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}
